### ISSUE TITLE
Is there any way to enable CORS ?

### ISSUE THREAD

**Issue by beatfreaker** [SlimerDude/afBedSheet#1]
@SlimerDude I am using this lib to create a server and export REST apis, and when I consume these REST apis from different UI app, browser is show CORS error.
So wanted to know if there is any way to allow CORS ?

**Comment by SlimerDude** [comment]
Hi @beatfreaker, CORS is very user and application specific, so there is no way to way to just *enable* or *allow* it.

From a BedSheet perspective, CORS is just about setting some HTTP response headers. For instance, to leave your webapp wide open by allowing it to be called from any domain, do this:

    @Inject HttpResponse res
    ...
    res.headers["Access-Control-Allow-Origin"] = "*"

Depending on what you're doing, you may also need respond to preflight / OPTION requests also.

Does this help any?

**Comment by beatfreaker** [comment]
@SlimerDude thank you for your explanation, It helped to achieve what I wanted.
